remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentaci칩n

nombres: Fernando S치nchez Arenas
submodulo: L칩gica de Programaci칩n
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/pagina-de-evidencias.appspot.com/o/..jpg?alt=media&token=9c6948db-e368-4ca2-b035-03f7e1968704

